### ISSUE TITLE
Unable to sign In

### ISSUE THREAD

**Issue by IAMIronmanSam** [gameplaycolor/gameplaycolor#101]
After so many tries and different accounts, all i get is Unable to sign In in IOS 12.2. Anyone help me out on this?

**Comment by redkaiser** [comment]
Hey, did you figure this out? I’m having issues myself.

**Comment by imethorsen** [comment]
There's a bug right now. We're working on it. I will update this thread when it's fixed.

**Comment by jbmorley** [comment]
This has been fixed for a while now. Closing.
