### ISSUE TITLE
Web App broken in Ipados

### ISSUE THREAD

**Issue by EmmanuelRoyOurBoy** [gameplaycolor/gameplaycolor#106]
A couple of notifications pop up and then a pitch black screen appears.

**Comment by nickydraz** [comment]
This is likely the same issue as #103 . I have created a PR #108 that should fix the issue.

**Comment by Zosoled** [comment]
Should be closed as duplicate of #103

**Comment by jbmorley** [comment]
Closing as a duplicate. Thanks @Zosoled.
