### ISSUE TITLE
BUSTED IOS13

### ISSUE THREAD

**Issue by no0bi1** [gameplaycolor/gameplaycolor#107]
What’s going on?

**Comment by 10acity420** [comment]
I have no clue, I think that the protocol they use for ios has been replaced creating a whole myriad of issues with the new ios update.

**Comment by nickydraz** [comment]
This is likely the same issue as #103 . I have created a PR #108 that should fix the issue.

**Comment by Zosoled** [comment]
Should be closed as duplicate of #103

**Comment by jbmorley** [comment]
Closing as duplicate.
