### ISSUE TITLE
Cannot get past the “access code” in installation

### ISSUE THREAD

**Issue by redkaiser** [gameplaycolor/gameplaycolor#116]
Earlier today the app was working fine. However, when I went on at around 9:30 pm it no longer showed any games. After attempts to turn my phone all the way off and on again, I deleted the app tried redownloading.
When I try to download I can get the app to add to my home screen. But then when I go to sign in, I can sign in but rather than show me the access code it just leaves me at a black screen.

Anything happen while I was away? I was just on a little while ago...

**Comment by nickydraz** [comment]
@imethorsen would this have anything to do with the auth changes you made recently? I think you've been working on some stuff since this issue was opened, so it could be all good now.

@redkaiser can you try again next chance you get? Let us know if the issue is still persisting.

**Comment by redkaiser** [comment]
@nickydraz Everything is working fine now! Thanks.
