### ISSUE TITLE
Game crashes and lose saves - Quick way to back up saves to iPhone

### ISSUE THREAD

**Issue by mbsync** [gameplaycolor/gameplaycolor#120]
Game play keeps crashing and when it does i lose the save data for whatever game I was playing, is there a quick way to back it up so I don’t play hours and lose it? Any help would be appreciated

**Comment by Josepsh** [comment]
Game play keeps crashing and when it does i lose the save data for Pokémon crystal game I was playing, is there a quick way to back it up so I don’t play hours and lose it? Any help would be appreciated

**Comment by jbmorley** [comment]
Are you loosing _all_ save data, or data since your last save? Thanks.

**Comment by jbmorley** [comment]
So in the interests of trying to get a better idea of the state of things and track clear issues that can be addressed, I'm going to close this as a dupe of #46 which tracks supporting import and export of saves.
