### ISSUE TITLE
Game Play doesn't work on iPadOS

### ISSUE THREAD

**Issue by Hansondpaul** [gameplaycolor/gameplaycolor#123]
I saved the app to the home screen, but the app simply opens as if I loaded the app in safari. If I scroll up I can see the menus for selecting a game, but it is loaded under the screen telling me how to install the emulator.

**Comment by imethorsen** [comment]
What device are you using this on?

**Comment by Hansondpaul** [comment]
I apologize for not specifying in the original post. This is on an IPad, 6th generation, with IPadOS 13.2.3.

**Comment by imethorsen** [comment]
Thanks for clarifying. Safari on iPadOS reports itself differently, so it's possible this is a side effect of that. We can investigate.

**Comment by Hansondpaul** [comment]
I apologize for not specifying in the original post. This is on an IPad, 6th generation, with IPadOS 13.2.3.

**Comment by Zosoled** [comment]
Should be closed as duplicate of #103

**Comment by brandosha** [comment]
Probably the same as this issue: https://github.com/brandosha/gameplaycolor/issues/4

**Comment by jbmorley** [comment]
Closing as duplicate.

**Comment by jbmorley** [comment]
I think I incorrectly closed this as a duplicate of #103. As it is, I think it's probably the problem where iPadOS reports itself as a Mac to convince sites to give it the desktop page.

**Comment by jbmorley** [comment]
I've updated the title to try to make it clearer what's going on with this issue.

**Comment by jbmorley** [comment]
Fixed in #185.
