### ISSUE TITLE
The app doesn’t work

### ISSUE THREAD

**Issue by Davidomar123** [gameplaycolor/gameplaycolor#124]
I saved the app on the home screen and when I opened it I found the same instructions on the page to put the app on the home screen and I didn't let myself register or play, help me.

**Comment by imethorsen** [comment]
Perhaps a duplicate of https://github.com/gameplaycolor/gameplaycolor/issues/123?

**Comment by Davidomar123** [comment]
What?

**Comment by imethorsen** [comment]
What device are you using this on?

**Comment by Davidomar123** [comment]
iPadOS iOS 13

**Comment by jbmorley** [comment]
Thank you for clarifying. It looks like this is the same as the issue that is being tracked here as issue https://github.com/gameplaycolor/gameplaycolor/issues/123. Game Play does not work with iPadOS 13.

**Comment by Zosoled** [comment]
Should be closed as duplicate of #103

**Comment by brandosha** [comment]
Probably the same as this issue: https://github.com/brandosha/gameplaycolor/issues/4

**Comment by jbmorley** [comment]
Thanks everyone for chiming in with your suggestions here. I'm pretty sure @brandosha is right: this is the issue where iPadOS pretends to be a Mac. I'm pretty sure that's fixed on his fork, but I've not had a chance to look at it yet (maybe one of these days we can collect all this wonderful work up in one place). Until then, I'm going to close this as a duplicate of issue #123 which is tracking the iPad issues.

I know this has been sitting open for a while now; I'll try to look into it soon.
