### ISSUE TITLE
Start and select buttons don’t work?

### ISSUE THREAD

**Issue by forshee1994** [gameplaycolor/gameplaycolor#125]
I downloaded a couple gb gbc Pokémon roms (pokemon brown and prism) and the start and select button don’t work on either game. Any ideas on how to resolve?

**Comment by Mastercarp** [comment]
Pokemon prism won't let you use the start or select buttons before a certain point in the story (don't worry, it's early on). It's the game, not the app.

**Comment by jbmorley** [comment]
Closing as invalid. Thanks @Mastercarp.
