### ISSUE TITLE
Loading GamePlayColor game states on GBC emulators on Mac

### ISSUE THREAD

**Issue by igtumidaj** [gameplaycolor/gameplaycolor#127]
I recently play Pokemon but after last update some of my unique Pokemons "disappered" and want to bring them back by using cheats in GBC emulator on Mac.
I downloaded a .gbc file (which I use to play on Iphone) from my Google Drive. However when I run it on any GBC emulator on Mac, there is no game state. What I see is only "New Game" and "Option".
My question is - how can I bring my game state from Iphone's GamePlayColor app to emulator on Mac?

**Comment by jbmorley** [comment]
@igtumidaj Unfortunately importing / exporting saved games is not supported in Game Play Color at the moment. @brandosha has a fork which supports saved games at https://github.com/brandosha/gameplaycolor/ and https://brandosha.github.io/gameplay/index.html.

I'm tracking the issue for Game Play Color as #46 so you're welcome to follow along there if you'd like.
