### ISSUE TITLE
Doesn’t work in new iOS versions

### ISSUE THREAD

**Issue by ghost** [gameplaycolor/gameplaycolor#129]
I have my iPad at iOS 13.3.1 and it never loads now. It doesn’t load for iOS 13.3 either
![5196582C-0B22-454B-8C63-948336994A94](https://user-images.githubusercontent.com/58752579/73859799-a0076980-4808-11ea-8ff7-f0cf792283d4.png)

**Comment by brandosha** [comment]
This appears to be a duplicate of #123 

It is also the same issue that I had on my fork: https://github.com/brandosha/gameplaycolor/issues/4

**Comment by jbmorley** [comment]
Thanks @brandosha. It is indeed a duplicate of #123. Closing as such.
