### ISSUE TITLE
iPhone Controller Support?

### ISSUE THREAD

**Issue by Vulcan013** [gameplaycolor/gameplaycolor#131]
Would it be possible to give this Controller Support with things like the Logitech Powershell from the iPhone 5 and SE Size Series? https://www.amazon.com/Logitech-PowerShell-Controller-Battery-Generation/dp/B00FHREO8K

**Comment by mayeslad** [comment]
Possibly PS4 and Xbox controllers would also be great now they can connect to iPhones?

**Comment by drinkdrpepper** [comment]
This is something I would very much appreciate. I have carpal tunnel and holding the phone to play hurts my fingers after a short while.

**Comment by jbmorley** [comment]
Duplicate of #57.
