### ISSUE TITLE
Audio nog working

### ISSUE THREAD

**Issue by eroithemaster** [gameplaycolor/gameplaycolor#133]
So when i first opened my game it asked me if i wanted to enable audio and i said yes. After closing it and opening it later my audio didnt work and it didnt ask me for it again. Still playing without audio

**Comment by jbmorley** [comment]
I've not seen this issue myself. Your iPhone needs to be unmuted for audio to work in Game Play. You might find it's useful to force quite the app and relaunch it.

**Comment by jbmorley** [comment]
We can re-open this issue if the problem persists.
