### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by AJPL88** [gameplaycolor/gameplaycolor#136]
Whenever I open the link, it shows up “Not Found. The page you are looking for cannot be found.” Is there a way to recover the data or fix this issue?

**Comment by jbmorley** [comment]
Are you able to provide any further information on this issue? Which 'link' are you opening? Thanks!

**Comment by jbmorley** [comment]
I'm closing this issue off. If you continue to have issues, please re-open, open a new issue, or add a comment. Thanks! 🙏🏻
