### ISSUE TITLE
Whenever I open gameplay color it’s just plain black. 

### ISSUE THREAD

**Issue by DCBAwesome** [gameplaycolor/gameplaycolor#139]
I know it’s not an iOS problem though because I’ve restarted my iPad many times and it still doesn’t work. I am on iPadOS 13.1.2 and it’s an iPad Pro I don’t know which generation it is though.

**Comment by DCBAwesome** [comment]
Also I had it working a while ago (like I could play games) then suddenly it started doing this

**Comment by jbmorley** [comment]
Thanks for raising the issue. I think this might be the same as #123 which is a result of Safari on iPadOS pretending to be a Mac.
