### ISSUE TITLE
Not sure if the Aspect ratio problem is fixed

### ISSUE THREAD

**Issue by SavageGaveItAllHeGot** [gameplaycolor/gameplaycolor#141]
Wanted to play an emulator and found this to be the only way to pass the time, and it seemed to work although I am unable to access features as my IPad Air 2’s screen requires it to have the options to continue playing, blocked by me needing to scroll and witness buttons that are out of my reach. Please try and find the issue, or state that it just isn’t possible for me

**Comment by SavageGaveItAllHeGot** [comment]
I also changed it from the desktop site, to the mobile site yet alas, it changes nothing

**Comment by cspeloso** [comment]
Hi, I posted something similar to this recently. I don’t think whoever created this updates it anymore / visits the site anymore

**Comment by jbmorley** [comment]
I'm still around. Just been busy lately. 🙃

Thank you both for raising your issues. Generally landscape seems to be pretty broken and unusable on a number of devices, so I'm trying to collect all these issues together under #89 and hopefully come out with something which approaches landscape in a far more flexible way.

I'm happy for your thoughts and feedback on that issue. 🙏🏻🎉
