### ISSUE TITLE
Save state reverts on Pokemon games

### ISSUE THREAD

**Issue by kenan-chiu** [gameplaycolor/gameplaycolor#142]
When I played Pokemon gold, and now currently Pokemon crystal, the save state reverts a little bit further back each day. It happens when I sleep and wake up to find the save state reverted. It probably has to do with the ingame clock on Pokemon Crystal & Gold. 
A good function would be a manual save state on Google Drive. thats all thanks

**Comment by jbmorley** [comment]
@Kiwi-Koala Thanks for raising the issue. Do you think this could be a duplicate of #137?

**Comment by jbmorley** [comment]
Tagging as duplicate in advance of @Kiwi-Koala's answer.
