### ISSUE TITLE
GPC freeze

### ISSUE THREAD

**Issue by dandrago** [gameplaycolor/gameplaycolor#143]
I’m not sure if this was warned about in the FAQ section, but every time I go back to the Home screen of my Iphone 7, if I reopen the app, it’s frozen and I can’t press anything. This only happens if a game is loaded, and the only fix seems to be restarting my phone each time. Is there something I can do about this?

For reference, the only game I’m playing is the latest version of Pokemon Prism, which is a rom hack of Pokemon Crystal.

**Comment by jbmorley** [comment]
@dandrago Sorry for taking time getting back to you. I've definitely noticed that iOS can sometimes put the Game Play Color webpage into a state where it never recovers from backgrounding. My guess is you're seeing it more often after you've used a few apps before returning? It seem to be made worse by lower RAM devices, which would make sense with an iPhone 7.

Fortunately the work around isn't too bad: if you just quit Game Play Color from the multi-tasking menu, it should work fine the next time you launch it; it shouldn't be necessary to restart the phone.

Take a look at https://support.apple.com/en-gb/guide/iphone/iph83bfec492/ios.

Hope this helps.
