### ISSUE TITLE
Can I clear safari cache without losing save data?

### ISSUE THREAD

**Issue by M4TH4N** [gameplaycolor/gameplaycolor#145]
Just wondering where the save for the game is.  I need to clear my cache and cookies on safari but I worry it will delete my save since it is a web based emulator.  If I can’t, then what would I have to not delete in advanced Safari cache settings in order to keep my save?  Thank you
- mathandd1@gmail.com

**Comment by jbmorley** [comment]
Sorry for taking time to look into this. Unfortunately, I think you'll loose your saved games if you clear your Safari cache right now. There's an issue open to support exporting games #46 but it's likely to be a while before this functionality is added. You could perhaps take a look at these instructions for exporting data if it helps. #100
