### ISSUE TITLE
Save only saves a bit

### ISSUE THREAD

**Issue by keith1407** [gameplaycolor/gameplaycolor#149]
The safe only saves half of what you have saved

**Comment by jbmorley** [comment]
Are you able to provide any more detail? Was this with a specific ROM? Thanks!

**Comment by jbmorley** [comment]
Possible duplicate of #142?

**Comment by jbmorley** [comment]
I'm not a big fan of closing things as stale, but without more information, I don't think as I can look into this. Closing as not planned.
