### ISSUE TITLE
A reoccurring issue with save states

### ISSUE THREAD

**Issue by Mastercarp** [gameplaycolor/gameplaycolor#151]
There is a feature where the game state is saved even after one logs out to answer messages or what not, which is nice!
But I have noticed how in some instances when I play, exit the app and then return, I think the app fails to connect to the drive properly. Quickest way to know when this happens is to try and switch games, because then I get a crash message. Unfortunately, I games can't save properly before the app resets, and I can't reset it manually but have to actually wait for it to do that itself.
Maybe you could add a "restart" button for the app, an option to not save states, or something else?

**Comment by Mastercarp** [comment]
my saving issues were resolved once I reinstalled the app on my phone, and blaming the save state feature was probably unjustified.

**Comment by jbmorley** [comment]
@Mastercarp Thanks for following up here. I'll close this one as 'invalid' for the time being then. We can always reopen / raise a new issue if we decide to revisit it.
