### ISSUE TITLE
Integrate @brandosha's changes

### ISSUE THREAD

**Issue by jbmorley** [gameplaycolor/gameplaycolor#189]
@brandosha has done some fantastic work on his fork of Game Play Color adding, amongst other things, save files and snapshotting. It would be fantastic to pull some (all?) of this back into Game Play.

We started this conversation on #122 which I've closed as it was old, and I'd love to pull these changes back piece by piece if possible so we can take the time to do some code reviews as we go.

**Comment by jbmorley** [comment]
https://github.com/gameplaycolor/gameplaycolor/pull/122#commitcomment-47141684

**Comment by jbmorley** [comment]
From @brandosha, https://github.com/gameplaycolor/gameplaycolor/pull/122#commitcomment-47141684:

> @jbmorley I would love to get some of my changes into the official build, there's just a few things we would probably need to take care of.
> 
> 1. Some of the code I added is a bit of a mess and doesn't fit well in the existing code style, probably want to clean it up
> 1. The Gameboy-Online core I am using is a fork, although I think the only modification on the main branch is one I just added to poll the game controller
> 1. Would you want to bring in all of the updates I have added or just a few of them?
>
> I'm actually a little bit glad you weren't around because it pushed me to contribute to my first "real" open source project. But anyway, I'm happy to work with you to update the official Game Play Color. 😀

**Comment by jbmorley** [comment]
1. I actually like some of the new code style and use of `async` etc. The Game Play JavaScript is _very_ out of date and would really benefit from some stylistic love (I'd really like to remove jQuery at some point). If you're up for it, I think some code reviews of your stuff could be a great way to start to set a better direction.
2. If the only change is the game controller polling, then I think we can get away without that. I've been working on #161 which does the polling in Game Play itself, rather than in the core. I think that will make it much easier to add custom controller configuration in the future if we want to do that, and support navigating the library with the controller.
3. I've not had a chance to fully go through your changes yet, but I suggest we go piece-by-piece if it's not too hard and see where it takes us.

I'm really happy to hear that you have enjoyed the process. Would you be interested in acting as a maintainer in the future?

**Comment by brandosha** [comment]
@jbmorley  Sorry it took me so long to respond, I have been pretty busy lately. But yes, this all sounds good. Do you need me to open up separate pull requests or issues or how do you want to go about this?

**Comment by jbmorley** [comment]
@brandosha No worries. I was busy for about 5 years, so I get it. 🙃

I'd love ot take it piece-by-piece as separate pull requests if that works for you. Of course it depends how hard it is for you to pull a feature out like that, but I think it's probably going to be the best way to review as we go. As a starting point, I think save game export / import is the most sought after feature. If you think there are other priorities, I'm totally open to suggestions.

I'd love your feedback (as issues or otherwise) on Game Play itself too (code base, coding style, etc) One of the great things about having multiple developers, especially with different backgrounds, is the ability to really lift up the standard of the code on the way.

**Comment by jbmorley** [comment]
@brandosha Maybe it would make sense to raise issues for the code we'd like to bring back so it's clear what the goals are? I guess there are a few open already that overlap too...

**Comment by jbmorley** [comment]
This has been sitting around for a while and we didn't really successfully move ahead with it. I'm going to close this explicit issue off and return to keeping #46 around to track the import/export functionality. Not to say we can't bring these changes in, but the issues are looking a little bloated right now.
