### ISSUE TITLE
Saved games and connect with others?

### ISSUE THREAD

**Issue by Chaotenmonster** [gameplaycolor/gameplaycolor#212]
Hey, I just want to know I you are working on saving games online, so I play the saved game at an other device. 
The other question I have is if you working on something to connect two device. Because I want to trade pokemons :D Do you think there will be an opportunity to do this somehow one day? 
Thanks a lot for the work! 
(Sorry for my bad english)

**Comment by jbmorley** [comment]
@Chaotenmonster You're looking at implementing support for save games? That sounds great. There's already an issue tracking this #46 where maybe you could add your thoughts.

As for link cable, it's definitely something I'd like to see one day too. That's tracked by #55.

I'm going to close this as a duplicate but it doesn't mean I want to stop the discussion, just encourage it onto the other two issues. I'm really grateful for both of your input. 🎉
