### ISSUE TITLE
Add support for GameShark 

### ISSUE THREAD

**Issue by gstreet66** [gameplaycolor/gameplaycolor#215]
New to GitHub. Hope this is the place to put requests. It would be awesome if this had a way to put in GameShark codes.

**Comment by jbmorley** [comment]
@gstreet66 This is indeed the place to put bugs and feature requests. Thanks for coming along for the ride. 👌🏻

There's actually an issue already open tracking this (#51) so I'm going to close this as a duplicate. Unfortunately I don't really have much time to work on this right now so it might be quite a while before I get around to adding the feature. I'm always open to contributions from others though.
