### ISSUE TITLE
No Sound After Sound Enabled (iOS 15.2)

### ISSUE THREAD

**Issue by abswan** [gameplaycolor/gameplaycolor#217]
Uploaded a ROM to the Google Drive and it plays fine, but there's no sound even though I enabled it on the pop-up. Sound switch is on loud with volume all the way up. On iOS 15.2 Safari.

**Comment by jbmorley** [comment]
@abswan I've noticed this can sometimes happen if the sound enable happens before the physical mute switch is turned off. Can I suggest disabling the the hardware mute/silence switch, force quitting Game Play, and trying again (assuming you've not done that already).

**Comment by jbmorley** [comment]
Going to close this issue as I've had no feedback. Please feel free to raise a new issue if this continues to be a problem.
