### ISSUE TITLE
Game display not scaling properly on iPad Mini 6 (iOS 15.2.1)

### ISSUE THREAD

**Issue by ewancube** [gameplaycolor/gameplaycolor#218]
Running Game Play 2.4.3 on iPad Mini 6 with mobile Safari (iOS 15.2.1) displays the game screen at approximately half the size it does on other iOS devices (even with same version). I suspect the fact that this iPad is a new model with revised screen dimensions to be the likely culprit. Please note that no functionality is impacted by this issue and it seems to be purely cosmetic.

![PlayColor_iPadMini6](https://user-images.githubusercontent.com/3604872/151620515-2db45d32-cac3-40e4-9db1-0fd9e909dd0f.jpg)

**Comment by jbmorley** [comment]
That doesn't look good does it. Thanks for taking the time to raise the issue @ewancube. I'll try to take a look at this and push an update.

**Comment by ewancube** [comment]
I’d like to expand this issue to include the horizontal layout which seems to have a slightly oversized game display. Again, this is purely cosmetic and has no functional impact.

![Untitled_Artwork](https://user-images.githubusercontent.com/3604872/152071532-33bb9896-060a-44d9-96de-606c32afed74.jpg)

**Comment by jbmorley** [comment]
Forward duping to #243.
