### ISSUE TITLE
Lost my save file

### ISSUE THREAD

**Issue by SCB16** [gameplaycolor/gameplaycolor#219]
So as the title suggests, I have lost my same file and I am gutted!

I was playing pokemon silver and I accidently deleted the ROM file from my google drive. I added the ROM file back to my drive from the exact same source as the first time but when I opened the app on my phone the game started from scratch!! 😥

I have already come to terms with the fact that I won't be getting it back but thought I would ask just in case I am missing something?

Thanks!

**Comment by jbmorley** [comment]
@SCB16 Sorry to hear you lost your save. Technically, I _think_ your saved game will still be present on your phone: if I remember correctly, the save is it's keyed by the Google Drive identifier for the ROM file, not the filename. That means that when you add the ROM back to Google Drive it's going to get a new identifier and Game Play doesn't know how to match it back. If you're fairly technically I suspect you could go into the database and update the key for the saved file to match, but it's likely to be a fairly involved process.

**Comment by SCB16** [comment]
Hi @jbmorley, thank you very much for the reply!

I was thinking the same thing about the save files being stored locally on my phone because you have the option to play the “GameBoy” even when you’re offline. I also see what you’re saying about the save file being keyed to a unique identifier.

I have tried investigating this further today but I cannot find any kind of data on the iPhone which links to the GameBoy shortcut as it’s not actually and app but also not a website as such. I have tried looking at local files on the phone and double checked Google Drive for any kind of save data but no luck. 

I might try attaching my iPhone directly to my PC later and try to find any kind of app data or databases but I’m not holding my breath.

Thanks again!

**Comment by gitteub1031** [comment]
Hi, 
can we have the location to get acces to the folder who manage est save all the save game. ? 
 i am on iphone  and i have no idea where i can find this folder 
thx 
Bastien

**Comment by Mitsun0bu** [comment]
Hey there !
Same question here, I have not lost anything. Everything is working fine, but it would be super nice to find the file that contains the save state so I can make a backup. If anyone knows where I can find it 🙏🏼

**Comment by pimp3x** [comment]
Someone solved this issue?

**Comment by jbmorley** [comment]
Related to #46.
