### ISSUE TITLE
Need trading/ evolve pokemon without trading

### ISSUE THREAD

**Issue by LetsPlay75** [gameplaycolor/gameplaycolor#221]
I put Pokémon blue on GPC and I can’t evolve some of my Pokémon without trading which I don’t think is possible. Any solutions?

**Comment by jbmorley** [comment]
I think the only way to address this would be with link cable support (#55) or manipulating save states (#46). With that in mind, I'm going to close this as a 'duplicate' (which isn't entirely true, but...).
