### ISSUE TITLE
Unable to download roms

### ISSUE THREAD

**Issue by LunarDragonX** [gameplaycolor/gameplaycolor#224]
The tutorial for downloading roms was outdated and didn’t work on my iPhone 12 when I tried to look at the updated version it had gotten a copyright strike from Nintendo so now I don’t know how to download roms.
Please help :(

**Comment by jbmorley** [comment]
@LunarDragonX Sorry for the late reply! The FAQ has instructions on how to add games to your Google Drive (https://gameplaycolor.com/faq/#add). The screenshots are all incredibly out of date (everyone's changing their UIs these days), but the workflow should be the same. As for _where_ to download ROMs, that's something you'll have to figure out for  yourself—technically you should only be using ROM images you've captured from your own games.
