### ISSUE TITLE
Add support for self hosted clouds

### ISSUE THREAD

**Issue by dl8bh** [gameplaycolor/gameplaycolor#225]
Not having a Google-Account anymore, I think it would be great to have the possibility to use other storage/cloud backends. Self hosted options like Nextcloud, Owncloud…. would be the best.

**Comment by jbmorley** [comment]
@dl8bh Late to reply, but yes, I hear you. As it happens, supporting Google Drive is looking increasingly untenable, so I'm planning to add support for adding local files. Tracking this work on #240 and #242.

**Comment by jbmorley** [comment]
It's not quite self-hosted clouds, but it should make Game Play usable as long as you can get the files there yourself. 🤞🏻
