### ISSUE TITLE
Rom-Hack of gave overwrites Original Game's Save Data

### ISSUE THREAD

**Issue by NintendoFan37** [gameplaycolor/gameplaycolor#226]
Hello!

A friend was playing Pokemon Crystal, and decided to start a Pokemon Crystal Rom-Hack.  When she saved the Rom-Hack, it also overwrote the save file for the original Crystal game.  My guess is that it thought the Rom-Hack was also Crystal, and put the save in the same location.

Has anyone else experience this bug? Is ther a way to recover the save for the original Game so it can be played?

Thanks!

**Comment by jbmorley** [comment]
That's a really weird experience and not something I'd have expected—internally save states are keyed on the Google Drive identifier for the ROM files themselves which should be unique to each ROM in your library.

**Comment by jbmorley** [comment]
I'm going to mark this issue as invalid and if we see it again we can raise a new issue or reopen this one.
