### ISSUE TITLE
save file sharing, full screen

### ISSUE THREAD

**Issue by singsungsangsung** [gameplaycolor/gameplaycolor#228]
Q1. Why can't you share the saved files with each other when you're playing game it with iPhone and iPad?
Can't share it with each other?

Q2. When I play 'game play color' on iPhone or iPad, can't I play it on the full screen?

**Comment by jbmorley** [comment]
There are currently no plans to support save state sync between devices or add full screen support. It's worth noting that the screen does scale up when hardware controllers are connected.
