### ISSUE TITLE
Support pressing A and B simultaneously

### ISSUE THREAD

**Issue by hunter1026** [gameplaycolor/gameplaycolor#231]
make it to where a and b buttons can be pressed simultaneously. its hard to play some games without this. super mario land for example.

**Comment by hunter1026** [comment]
also offline support isnt working anymore

**Comment by jbmorley** [comment]
Updated the title to match the first request. Issue #210 is tracking some an issue related to offline support, though I expect this to change significantly when #242 lands.

**Comment by jbmorley** [comment]
Closing this as won't fix.
