### ISSUE TITLE
Unexpected slow down in Pokémon

### ISSUE THREAD

**Issue by jbmorley** [gameplaycolor/gameplaycolor#233]
One of our users has been seeing an unexpected slowdown in Pokémon

> I’ve been playing Pokémon a lot recently and have been using 3x game speed. I was having no problems until randomly the speed went back to normal yet still being in 3x speed. I thought maybe switch it back to 1x but when i did the game was 3x slower than normal speed. I restarted my phone and it doesn’t do anything, I’ve tried doing eveyrthing and the same glitch is happening on every game. I’ve logged out of google drive and logged back in and nothing has been fixed. Please get back to me because it’s making the game very difficult to play. Thank you have a good day.

**Comment by robfjord** [comment]
This is happening to me too. Hope it gets fixed.

**Comment by bigpeenjanine** [comment]
I made an account just to answer this one. 

The issue is caused by low power mode. Disabling low power mode in IOS settings will fix the issue

**Comment by jbmorley** [comment]
Thanks for checking in @bigpeenjanine. I'm going to close this as not planned / invalid.
