### ISSUE TITLE
Please continue developing this!

### ISSUE THREAD

**Issue by GamePlayColorFan** [gameplaycolor/gameplaycolor#234]
I love GamePlay Color, and I’m disappointed to see nothing new has come out for it since 2021.  In the off chance anyone from InSeven sees this, please tell me this project isn’t completely abandoned?  I got concerned seeing how many older support tickets seem to have not been followed up on.  I’d be interested to see if save files can be hosted in Google Drive and if there’s a way to re-enable sound if the sound turns off in a game without having to restart the app entirely.

Please don’t let this beautiful thing die and become defunct!

**Comment by GamePlayColorFan** [comment]
Also on my wishlist is a GBA emulator (although I wonder how L+R might work on a phone, now that I think about it…) and link cabling so you can trade Pokémon, for example!  🥰

**Comment by jbmorley** [comment]
Thank you for the encouragement! Going to close this issue as there's not any clear action, but the message is received. 🙏🏻
