### ISSUE TITLE
Full screen issue

### ISSUE THREAD

**Issue by mrleiricy** [gameplaycolor/gameplaycolor#238]
I noticed when playing that there is a few millimeters of space at the top that’s white. I’m running iOS 17 on a iPhone 11.
![IMG_1073](https://github.com/gameplaycolor/gameplaycolor/assets/96336655/211631ec-785b-4a0f-bc76-c01d58219997)

**Comment by jbmorley** [comment]
Unfortunately, I'm pretty sure this is a design choice with iOS 17 and not something I can change. If you want it to go away you can put your phone in dark mode while you're playing Game Play. 🤦🏻‍♂️
