### ISSUE TITLE
Google is Blocking access

### ISSUE THREAD

**Issue by terryB23** [gameplaycolor/gameplaycolor#240]
Logged out and tried logging into the same account which has worked for the last 5 years and was hit with a “This app is blocked. This app tried accessing sensitive info in your Google Account. blah blah blah”. Did some research and a lot of others have this issue but can resolve it with advanced settings by allowing it anyway. In my case however there is no option for advanced settings. Any suggestions or others with this issue?  Love Game Play Color with my whole heart, please help a brother out.

**Comment by jbmorley** [comment]
Google's been getting increasingly picky about validating apps and organizations that integrate with Google Drive and I just couldn't face going through the process all over again for the nth time. I'd not realized it would get so aggressively blocked this time around—that sucks.

My thinking right now is that I'm going to strip Google Drive out entirely and just let people upload ROMs directly from their iPhone (iCloud Drive, etc).

Out of interest, are you signing in on a new phone, or did you get automatically logged out?

**Comment by terryB23** [comment]
Same device, automatically logged out. I had been playing the day before with no problems.

**Comment by HellDan91** [comment]
> Google's been getting increasingly picky about validating apps and organizations that integrate with Google Drive and I just couldn't face going through the process all over again for the nth time. I'd not realized it would get so aggressively blocked this time around—that sucks.
> 
> My thinking right now is that I'm going to strip Google Drive out entirely and just let people upload ROMs directly from their iPhone (iCloud Drive, etc).
> 
> Out of interest, are you signing in on a new phone, or did you get automatically logged out?

Could you fix the problem meanwhile?

**Comment by jbmorley** [comment]
Update, cross-posted from dupe #241:

> Yeah. This all sucks, I agree. Google's been getting more and more painful here and it's not something I'm not willing to keep up with any more—I've already verified the app multiple times but they keep changing the goal posts. With all the kinds of changes lately, I don't really trust the platform APIs to hang around in a way I can use.
>
> So! I'm currently working on a rework of Game Play which drops support for Google Drive entirely and lets you add games from your local device. It also drops the iOS restriction so Android users should be able to have fun. My plan, right now, is to ensure that games you've already added from your Google Drive (downloaded and played), will remain in your local archive and save states will be preserved.
> 
> The theory is that these changes will generally make Game Play more reliable and ensure it keeps working into the future irrespective of what Google or others decide to do.

**Comment by jbmorley** [comment]
@HellDan91 In direct response to your request—I took a look at just jumping through the hoops yesterday and after about half an hour of clicking around it wasn't at all clear exactly which process I have to go through. At this point, it's just me maintaining Game Play, and I'd rather spend my limited time working on a more permanent fix.

**Comment by jbmorley** [comment]
If you're interested in following along with progress, the development PR is at https://github.com/gameplaycolor/gameplaycolor/pull/242.
