### ISSUE TITLE
Support different console appearances per cartridge

### ISSUE THREAD

**Issue by jbmorley** [gameplaycolor/gameplaycolor#48]
Game Play Color currently displays uses a Game Boy Color theme for all cartridges. It'd be nice to show a Game Boy theme when playing original Game Boy carts, and a Game Boy Color theme only when playing Game Boy Color carts.

**Comment by Shawnjoseph2001** [comment]
Additionally, it would be cool if you could choose a specific theme per cartridge- for example, launching LOZ- Link's Awakening DX in green, and Pokemon Yellow in Yellow.

**Comment by jbmorley** [comment]
Won't fix.
