### ISSUE TITLE
Add support for cheats such as Game Shark or Game Genie

### ISSUE THREAD

**Issue by jbmorley** [gameplaycolor/gameplaycolor#51]

**Comment by internet-Fur** [comment]
Has this been finally finished yet?

**Comment by skooma42** [comment]
Update?

**Comment by LordRahl85** [comment]
Update yet?

**Comment by mosesjlee** [comment]
Update yet?

**Comment by staindedboxerz** [comment]
Any update on this?

**Comment by jbmorley** [comment]
Thanks for expressing your interest. As it is, it's not likely that I'n going to get around to this any time soon. But I'm always happy to accept pull requests. 🙃

**Comment by jbmorley** [comment]
There are many other options for emulation on iOS these days. Closing as won't fix.
