### ISSUE TITLE
Add support for hardware keyboards and game pads

### ISSUE THREAD

**Issue by jbmorley** [gameplaycolor/gameplaycolor#57]

**Comment by yeahdef** [comment]
I recently purchased [this product](https://www.amazon.com/gp/product/B00FHREO8K/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1) and I am interested in making it compatible with your project. I was reviewing the [official apple docs on game controllers](https://developer.apple.com/library/ios/documentation/ServicesDiscovery/Conceptual/GameControllerPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40013276-CH1-SW1) and they do not mention controlling web-based games. maybe we could discuss how these button press events could be passed to gameplay?

**Comment by jbmorley** [comment]
Coincidentally I was looking at this in an Apple Store yesterday. If it emulates hardware buttons in Safari and we can get a comprehensive list of what those are, there shouldn't be anything stopping us supporting that.

Are you able to find out the key mappings?

**Comment by yeahdef** [comment]
yeah - It was only $8 on amazon so a took a chance on it. I will see if I can dive into the key mappings and how it is transmitted to Safari. Seems like a viable option considering it is a "official" controller. I think this project is a great candidate for a game controller like this. The touch controls are kind of hard for some precise mob avoidance needed in Link's Awakening. :)

**Comment by jbmorley** [comment]
Fantastic. Let me know how you get on. There's already support for hardware keys internally (I need some way to test it on the desktop during development), so it should be pretty easy to add if it can emulate key events.

**Comment by yeahdef** [comment]
I have too many ideas for my weekend, but this just went to the top of the list. :)

**Comment by yeahdef** [comment]
I tried quite a bit of debugging, but couldn't find a way to capture the raw keycodes that the gamepad might be sending to Safari on iOS. I also found that [support is low](http://caniuse.com/#feat=gamepad) for the [gamepad api](https://www.w3.org/TR/gamepad/) in mobile browsers. I think it is fairly likely, that this particular gamepad keycodes are not perceived by the browser b/c it does not mimic a keyboard keycode for instance. Maybe with a different gamepad that merely sends the equivalent of keyboard keypress events, it might work.

**Comment by jbmorley** [comment]
@yeahdef Thanks for looking into it. Hopefully we'll find some that are easier to support.

**Comment by jbmorley** [comment]
Now that iOS supports it, I've got rudimentary support working using the Gamepad API (https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API). Currently working on refining the user experience and lifecycle around connecting / disconnecting controllers.

**Comment by jbmorley** [comment]
I'm pretty sure this has already been done. Closing as fixed.
