### ISSUE TITLE
Save and restore the game state when the app is backgrounded / foregrounded

### ISSUE THREAD

**Issue by jbmorley** [gameplaycolor/gameplaycolor#58]
It would be great if it were possible to save game state when the application is backgrounded and then restore this when foregrounded. Historically this has been impossible due to limitations Mobile Safari on iOS. We should explore whether this has changed.

**Comment by jbmorley** [comment]
Camille Kander suggests on twitter that the `visibilitychange` event might now work:

> @insevenlimited ‘visibilitychange’ seems to work fine. Would it do the job?

(See https://twitter.com/Xzoky/status/704819724874416128).

**Comment by Andrew5569** [comment]
Is there currently a way to save the game state then reload it? If that exists I could work on this feature

**Comment by Andrew5569** [comment]
Thanks @Shawnjoseph2001. Just to clarify for others it's actually [alpha.gameplaycolor.com](http://alpha.gameplaycolor.com/) and it has save and restore implemented. The source for save and restore is available on the [jbm-master-save-restore](https://github.com/gameplaycolor/gameplaycolor/tree/jbm-master-save-restore) branch.

**Comment by Andrew5569** [comment]
The proposed solution by Camille will not work because there is a bug with the Page Visibility API on iOS 

> [4] From iOS 11.0.2 onwards, the values are not correct in standalone mode (when you press "Add to Homescreen") and when the screen is locked (you pressed the power button). The value for hidden is false and visibilityState is visible.

[see MDN](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#Browser_compatibility)

I'll see if I can come up with another solution
