### ISSUE TITLE
Cartridge artwork doesn't update if the file on Google Drive changes

### ISSUE THREAD

**Issue by jbmorley** [gameplaycolor/gameplaycolor#63]
Once the artwork for a given ROM has been cached in the local database, Game Play makes no further attempt to check on Google Drive. This means that changes to that file (or even deleting that file) doesn't cause a corresponding update in the game library.

Game Play should cache the mtime and identifier of the artwork file on Google Drive and update the locally cached copy if it is found to have changed.

**Comment by valthor-uwu** [comment]
Is there anyway to fix that

**Comment by jbmorley** [comment]
Tracking this along with the work to add local file support and remove Google Drive support; it should be possible to just upload a suitably named file over the top.

**Comment by jbmorley** [comment]
On further consideration, I'm going to close this as won't fix since that better matches what's going on. The new implementation will support manually updating artwork, but it's a completely different flow.
