### ISSUE TITLE
Patched ROMs appear as audio files on Google Drive 

### ISSUE THREAD

**Issue by orikun** [gameplaycolor/gameplaycolor#69]
Patched ROMs show as audio files on google drive, and even though ending in .gb/.gbc does not show in the games libary.

**Comment by jbmorley** [comment]
Just updated the title to make it easy to see the issue details at a glance.

**Comment by jbmorley** [comment]
Is anyone still looking for a fix for this?

**Comment by MDMcNugget** [comment]
I am. My ROM hack of Pokémon Blue with the .gb extension is being considered an audio file in Google Drive.

**Comment by jbmorley** [comment]
I've just released 2.4.3 which should address this issue. I'd love to hear how you all get on with the release.

**Comment by Pixel3D** [comment]
Now works with my patched roms. Just tried Pokemon Red Full Color Hack and Pokemon Prism. Great!

**Comment by jbmorley** [comment]
@Pixel3D Thanks for checking it out! Really happy to hear it's working for you. I'm going to close this as fixed then. 🎉

**Comment by MDMcNugget** [comment]
Works perfectly now! Thanks a bunch 😁
