### ISSUE TITLE
Improved on-screen / touch controls

### ISSUE THREAD

**Issue by kasik96** [gameplaycolor/gameplaycolor#70]
Hi,
it will be awesome if you add Vrtiual Joystick as replacement of classic control. Be able to turn it on and off in settings. Its better for games like Mario and Zelda, becouse you dont need to have finger on specific spot, just place it on left side of screen and move.
You can use joystick.js http://jeromeetienne.github.io/virtualjoystick.js/examples/basic.html 
Thanks 👍

**Comment by jbmorley** [comment]
Thanks for the suggestion. I'll keep it in mind when working on future releases.

**Comment by jbmorley** [comment]
Since this was the first issue asking for improvements to the on-screen / touch controls, I've updated the titles accordingly, I plan to dupe some of the other issues to this so we can collect all the requests in one place.

**Comment by jbmorley** [comment]
> Make the buttons bigger please it hard to use on iPad. Sincerely, Aidan.

**Comment by jbmorley** [comment]
I still really love the idea of this, but at this point I'm shifting into more of a maintenance mode for Game Play and no longer planning on adding new features—there are just too many other things to work on and so many far better options for emulation on iOS these days. Closing as won't fix.
