### ISSUE TITLE
NES ROM support

### ISSUE THREAD

**Issue by Shawnjoseph2001** [gameplaycolor/gameplaycolor#76]
It would be nice to see support for NES ROMS directly in Game Play Color, as the NES is similar in power to the Game Boy Color, and a working web based iOS NES emulator already exists (webn.es), but with much less features than the Game Play Color.

**Comment by jbmorley** [comment]
Good suggestion. I'd certainly like to move to a world where Game Play does more than just Game Boy games.

**Comment by jbmorley** [comment]
@Shawnjoseph2001 Only 5 years late, I'm going to close this as a duplicate of #155 where I'll try to actually keep track of additional console requests. 😅
