### ISSUE TITLE
If possible- vibrate on button press

### ISSUE THREAD

**Issue by Shawnjoseph2001** [gameplaycolor/gameplaycolor#78]
back when the Date Trick was active, GBA4iOS had a feature where the phone would vibrate whenever you tapped a controller button. I'm not sure if WebKit allows you to do this, but it would be cool if you could add that feature into Game Play Color.

**Comment by Nythepegasus** [comment]
This seems like a great idea! There also seems to be a somewhat easy way to do this, I'll try and code it and submit it.

**Comment by Nythepegasus** [comment]
So, an update on what I said earlier, it doesn't seem to work for iOS, but it works for android.

**Comment by pvinis** [comment]
unfortunately it's not possible because the emulator is running as a web app and that doesn't have access to vibration. I wanted to try to make a wrapper app but then there is the problem that is not allowed in the app store.

**Comment by shawnjoseph200** [comment]
We could go the GBA4iOS route and make it available through enterprise distribition, or send it as an IPA for Cydia Impactor if necessary.

**Comment by Nythepegasus** [comment]
You can get GBA4iOS if you use 'TutuHelper', no jailbreak required, if you use the free version, not vip.

**Comment by pvinis** [comment]
ok I will research a bit about that way.

**Comment by pvinis** [comment]
i checked out tutuhelper and builds.io, and they are both paid, apparently $10 per device per year. so I dont think thats a great alternative.. unless there is a free one, or many people that use emulators already pay for one of those.

**Comment by Nythepegasus** [comment]
@pvinis There is a free version on their website. 
![screen shot 2017-01-21 at 10 53 37 am](https://cloud.githubusercontent.com/assets/17764867/22175690/19212df8-dfc8-11e6-9df7-6bb62a0ac249.png)

**Comment by pvinis** [comment]
I feel stupid :p I didn't see. I will try that out.

**Comment by jbmorley** [comment]
Closing as won't fix.

Unfortunately iOS _still_ doesn't have support for `Navigator.vibrate()` (see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate#browser_compatibility) so there's really nothing we can right now. I really hope they add support for this one day, but I'm not holding my breath. 😢

Maybe we can at least make this work on Android if we ever get around to #68. 🙃
