### ISSUE TITLE
Error when starting build of gameplay

### ISSUE THREAD

**Issue by trilleplay** [gameplaycolor/gameplaycolor#79]

**Comment by Nythepegasus** [comment]
For all I know, there is no file called 'swfobject.js', and that is what is throwing the error. I have no answer on how to fix it.

**Comment by pvinis** [comment]
indeed. i also tried building it and it works fine. did you do the submodules part in the readme? or maybe you changed the path to get gameboy-online from somewhere else, and its not correct, or different version that moved that file..
