### ISSUE TITLE
App won't load

### ISSUE THREAD

**Issue by dominikaaaa** [gameplaycolor/gameplaycolor#84]
When loading "Game Play encountered an issue. Send crash report?" Crash report: https://pastebin.com/K12RETDB
When in airplane mode it won't show ROMs because I've never loaded then from Google drive (but I do have the ROMs on my drive with covers)
So in short I can't play any ROMs because with WiFi app won't start without WiFi ROMs aren't loaded

**Comment by Nythepegasus** [comment]
This seems to be an issue with Safari. Can you see the ROMS on Google Drive while in airplane mode?

**Comment by ChristoferMinestar** [comment]
Yes

*Christofer*

**Comment by ChristoferMinestar** [comment]
I saved them to offline in Drive

*Christofer*
