### ISSUE TITLE
401 deleted_client error

### ISSUE THREAD

**Issue by Lustle** [gameplaycolor/gameplaycolor#87]
Went to try and use the app today. And it had kicked me out to the "sign in" / "enter access code" screen. So I tried to sign back in to get another access code. And got an error screen. Says:

Google

401. That's an error.

Error: deleted_client

The OAuth client was deleted.

Request Details
That's all we know.

Just wondering what's going on? If I need to reset something on my google drive side? Or if it's an app error with contacting google drive and getting authorization. Which is what is sounds like to me.

Anyone else getting this? Anyone got a fix?

Thanks.

**Comment by Mlee77** [comment]
I had the same problem today!

**Comment by DannyOcean89** [comment]
I had the same issue today and have been searching for hours and no luck. It definitely seems to have to do with sign in authorization with google drive and gameplay. Still no answers

**Comment by COOLIRON2311** [comment]
Well, I guess google finally closed it. Or maybe it's some error... Or an update...

**Comment by Nikhil327** [comment]
Same

**Comment by Nikhil327** [comment]
When you request details it says 
![img_0004](https://user-images.githubusercontent.com/25268184/30002675-8b501388-907d-11e7-95e4-3f281a804482.PNG)

**Comment by COOLIRON2311** [comment]
Yes, mine details request displays the same info as yours. There must be something wrong on Google's side. The only problem is that it must be fixed by the developer, but I assume that he doesn't know about this problem.

**Comment by TheFilipOwiecki** [comment]
Same... I hope our saves won't be deleted ;(((

**Comment by lbrowning5388** [comment]
Same issue.. unfortunately I think I'm going to lose all of my saved games.

**Comment by ZynXc** [comment]
Same and if I lose my saved data I am going to be PISSED cause I am so close to completing Crystal

**Comment by Mlee77** [comment]
InSeven Limited posted on twitter: 
InSeven Limited‏ @insevenlimited  6h6 hours ago
 We’re currently exploring why authentication is failing. Don’t remove the app from the home screen and saves should be safe.

**Comment by COOLIRON2311** [comment]
Yay! They know about the problem! We will be saved soon!) AND VERY IMPORTANT THING!
You can scroll up the aunthification massage and play some of your games. So everything seems to be fine.

**Comment by Servese** [comment]
Good to hear that it is getting fixed. I was about to open an issue thread (or whatever it is) but I saw this here. I was dumb enough to remove game play and add it again so goodbye to my saves. Great work InSeven and I will look forward to the return of game play color.

**Comment by COOLIRON2311** [comment]
![img_2916](https://user-images.githubusercontent.com/31288825/30048664-f80ac088-921f-11e7-89f9-018056a8da8a.PNG)

**Comment by jbmorley** [comment]
Closing as fixed.
