### ISSUE TITLE
Sound still not working in ios 11

### ISSUE THREAD

**Issue by Servese** [gameplaycolor/gameplaycolor#88]
The official ios 11 release is in a few days and I am running my ipad air on ios 11 gm (gold master beta, almost completely polished off) and the sound still isn’t working. I am aware that someone has already posted an issue about this but I am just pointing out that is isn’t fixed yet. It would be greatly appreciated if this issue could be fixed.

**Comment by Servese** [comment]
My sound is on full and ringer is on

**Comment by COOLIRON2311** [comment]
Same issue

**Comment by COOLIRON2311** [comment]
Well, someone going to fix it?

**Comment by Servese** [comment]
This will probably be fixed by the time ios 12 comes out!
