### ISSUE TITLE
Landscape layout is broken on many devices

### ISSUE THREAD

**Issue by NinjolasNJM** [gameplaycolor/gameplaycolor#89]
In landscape mode the start and select buttons are inside the screen, and the d-pad and b button touch the bezel. The screen is touching the bottom.

**Comment by Nythepegasus** [comment]
Hey, which device are you specifically experiencing this issue? It'd help others recreate the issue, giving it more of a chance to be fixed.

**Comment by Hossinto** [comment]
Yes my landscape looks weird too I am using an iPhone SE iOS 11. the screen is so big it’s passes the bottom of the phone buttons are on the main screen, in other words make the screen fit with in the boundaries place the d pad and buttons at the side thanks for reading my problem hope an update comes out soon

I wish there was some way to upload a picture so u can see for your self.

**Comment by jbmorley** [comment]
I've updated the title to try to capture the broader set of issues we've been seeing here.

- buttons below the fold and impossible to reach
- buttons obscuring the screen

**Comment by dougpieters** [comment]
Any update on this? Something with the screen size of the Max seems to cropping the display in. Currently on iPhone 13 Pro Max and also experienced this same issue on iPhone 12 Pro Max. But I have not experienced the issue in landscape on an iPad Pro 11", iPhone 13 Pro, or an iPhone 13 Mini.

**Comment by derekedelaney** [comment]
This is a CSS issue in the gameboy.css file. I was able to update `@media only screen and (min-width: 768px) {` with `@media only screen and (min-width: 768px) and (orientation: portrait)` and the screen fits the phone in landscape.

**Comment by jbmorley** [comment]
Forward duping to #243.
