### ISSUE TITLE
Toggle color correction

### ISSUE THREAD

**Issue by ruvaldak** [gameplaycolor/gameplaycolor#90]
It seems that this emulator has some form of color correction - or maybe it’s  just my screen? Anyway, if it does apply a form of color correction, it’d be great to be able to disable that.

Color correction can be seen in retroarch’s gambatte libretro

**Comment by blair34848i** [comment]
hi

**Comment by no0bi1** [comment]
Hi

**Comment by jbmorley** [comment]
I suspect what you're seeing here is actually a result of how the original colors are rendering on modern screens---there's actually no color correction going on. Many emulators approach this by adding color correction to product colors that better match the original devices.

That said, this isn't a feature I plan to add---there are now exciting new options for emulation on iOS so I don't think it makes sense to significantly grow the functionality of Game Play at this point beyond ensuring it works reliably into the future.
