### ISSUE TITLE
Development environment setup

### ISSUE THREAD

**Issue by 8eecf0d2** [gameplaycolor/gameplaycolor#93]
Just wondering how to setup a development environment?

I've followed the readme instructions and builds are working on my iPhone but I can't figure out how to run the site with desktop browsers - can't get past the instructions splash screen.

**Comment by nickydraz** [comment]
I'm not sure if you can run it on the desktop. I'm not overly familiar with how PWAs are supposed to work, but for this app you normally add it to your phone's home screen before it'll get past the instructions screen, even on mobile Safari.

For me, I followed these steps to allow for debugging of the mobile version:

1. On iPhone -> Settings -> Safari -> Advanced -> Enable "Web Inspection"
2. Connect iPhone to Mac/Macbook
3. Open desktop Safari
4. In the "Develop" menu of desktop Safari, you should see both your Mac/Macbook and iPhone listed
5. Select the iPhone, select the window you want to inspect
6. This will open a dev tools window that is tied to the mobile Safari window. Can debug/troubleshoot from there as needed.

**Comment by jbmorley** [comment]
@8eecf0d2 The splash screens shows up because Game Play needs to be convinced it's running on a phone. You can use `sizes.html` instead and you should find that the emulator will load.
