### ISSUE TITLE
Won't Load My Games

### ISSUE THREAD

**Issue by nitrodragon** [gameplaycolor/gameplaycolor#94]
I put _every single GB/GBC ROM_ in my Google Drive and now it won't load anymore. Is this an anomaly or was GPC not written to handle a collection of such magnitude?

**Comment by jbmorley** [comment]
@nitrodragon Did you ever get this working? I guess it might struggle a bit with a lot of files, but there's no limit I'm aware of.

**Comment by jbmorley** [comment]
Closing this issue as we've not seen any issues from others and I'm fairly sure it's not a limitation. Things will change significantly when #242 lands too.
