### ISSUE TITLE
Games not loading on iPad

### ISSUE THREAD

**Issue by djfreewill** [gameplaycolor/gameplaycolor#99]
I use GPC with a 10.5 inch iPad with iOS 12.2, and I put my roms into Google Drive. Of course I clicked the grayed out roms to download. It looks like it works, but it won't load. It would spin for some time, but would stop. Plenty of my roms do not load, which irritates me.

**Comment by jbmorley** [comment]
@djfreewill I think this might have been an a storage limitation issue. I know you asked the question a while ago (sorry I didn't get around to taking a look until now), but if you still use Game Play, I _hope_ you find it's now working more reliably after we deployed the new storage solution (thanks to @nickydraz).

**Comment by jbmorley** [comment]
Closing for the time being. Please feel free to add a comment / re-open if you're still experiencing issues. 🙏🏻
